# Generated by Django 3.2.4 on 2021-06-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
    ]
