# Generated by Django 3.2 on 2021-05-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название проекта')),
                ('description', models.CharField(max_length=300, verbose_name='Описание проекта')),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('url_address', models.URLField()),
                ('date', models.DateTimeField(verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
                'ordering': ['-date'],
            },
        ),
    ]
